name: Validate Specs

# Execute workflow on push to master or on any pull request
on: 
    push:
      branches:
        - master
    pull_request:

jobs:
  validate:
    name: Validate Specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
            python-version: '3.x'
      - run: pip install openapi-spec-validator
      - run: find ./specs/*.yaml | xargs python -m openapi_spec_validator